on: [push, pull_request]
name: tests
jobs:
  screenshooter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        galaxy_version: [release_21.01]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: create screenshots from ${{ matrix.galaxy_version }}
        run: |
          wget https://github.com/galaxyproject/galaxy/archive/${{ matrix.galaxy_version }}.tar.gz
          tar xvzf ${{ matrix.galaxy_version }}.tar.gz | tail
          cd galaxy-${{ matrix.galaxy_version }}
          SCREENSHOTS_DIR=${{ github.workspace }}/screenshots
          mkdir -p "$SCREENSHOTS_DIR"
          GALAXY_TEST_SCREENSHOTS_DIRECTORY=$SCREENSHOTS_DIR ./run_tests.sh -selenium lib/galaxy_test/selenium -- -m gtn_screenshot -m local
          echo "SCREENSHOTS_DIR=$SCREENSHOTS_DIR" >> $GITHUB_ENV

      - name: Upload screenshots to S3
        run: |
          echo $SCREENSHOTS_DIR
          aws configure set aws_access_key_id ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.TESTS_AWS_SECRET_KEY_ID }}
          aws configure set default.region us-east-2
          aws s3 cp --recursive $SCREENSHOTS_DIR s3://galaxy-tests/galaxy-gtn-screenshots/local --acl public-read
          aws s3 ls s3://galaxy-tests

      - name: Cache pip dir
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/galaxy-${{ matrix.galaxy_version }}/.venv
          key: pip-cache-${{ matrix.galaxy_version }}